// 微隔离 gRPC 协议定义
// Agent <-> Controller 通信协议

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.5
// source: microseg.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_microseg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_microseg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_microseg_proto_rawDescGZIP(), []int{0}
}

type ConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigResponse) Reset() {
	*x = ConfigResponse{}
	mi := &file_microseg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigResponse) ProtoMessage() {}

func (x *ConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_microseg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigResponse.ProtoReflect.Descriptor instead.
func (*ConfigResponse) Descriptor() ([]byte, []int) {
	return file_microseg_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReportResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Code           int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ReportInterval uint32                 `protobuf:"varint,3,opt,name=report_interval,json=reportInterval,proto3" json:"report_interval,omitempty"` // 建议的上报间隔（秒）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReportResponse) Reset() {
	*x = ReportResponse{}
	mi := &file_microseg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResponse) ProtoMessage() {}

func (x *ReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_microseg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResponse.ProtoReflect.Descriptor instead.
func (*ReportResponse) Descriptor() ([]byte, []int) {
	return file_microseg_proto_rawDescGZIP(), []int{2}
}

func (x *ReportResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ReportResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReportResponse) GetReportInterval() uint32 {
	if x != nil {
		return x.ReportInterval
	}
	return 0
}

type AgentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	HostId        string                 `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	HostName      string                 `protobuf:"bytes,3,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Platform      string                 `protobuf:"bytes,5,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	mi := &file_microseg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_microseg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_microseg_proto_rawDescGZIP(), []int{3}
}

func (x *AgentInfo) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentInfo) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *AgentInfo) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *AgentInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentInfo) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

type RegisterResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Code           int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ClusterId      string                 `protobuf:"bytes,3,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	ReportInterval uint32                 `protobuf:"varint,4,opt,name=report_interval,json=reportInterval,proto3" json:"report_interval,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_microseg_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_microseg_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_microseg_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponse) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *RegisterResponse) GetReportInterval() uint32 {
	if x != nil {
		return x.ReportInterval
	}
	return 0
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Stats         *AgentStats            `protobuf:"bytes,3,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_microseg_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_microseg_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_microseg_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HeartbeatRequest) GetStats() *AgentStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_microseg_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_microseg_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_microseg_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *HeartbeatResponse) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type AgentStats struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WorkloadCount   uint32                 `protobuf:"varint,1,opt,name=workload_count,json=workloadCount,proto3" json:"workload_count,omitempty"`
	ConnectionCount uint32                 `protobuf:"varint,2,opt,name=connection_count,json=connectionCount,proto3" json:"connection_count,omitempty"`
	PolicyCount     uint32                 `protobuf:"varint,3,opt,name=policy_count,json=policyCount,proto3" json:"policy_count,omitempty"`
	MemoryUsage     uint64                 `protobuf:"varint,4,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	CpuUsage        float32                `protobuf:"fixed32,5,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AgentStats) Reset() {
	*x = AgentStats{}
	mi := &file_microseg_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStats) ProtoMessage() {}

func (x *AgentStats) ProtoReflect() protoreflect.Message {
	mi := &file_microseg_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStats.ProtoReflect.Descriptor instead.
func (*AgentStats) Descriptor() ([]byte, []int) {
	return file_microseg_proto_rawDescGZIP(), []int{7}
}

func (x *AgentStats) GetWorkloadCount() uint32 {
	if x != nil {
		return x.WorkloadCount
	}
	return 0
}

func (x *AgentStats) GetConnectionCount() uint32 {
	if x != nil {
		return x.ConnectionCount
	}
	return 0
}

func (x *AgentStats) GetPolicyCount() uint32 {
	if x != nil {
		return x.PolicyCount
	}
	return 0
}

func (x *AgentStats) GetMemoryUsage() uint64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *AgentStats) GetCpuUsage() float32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

type AgentStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	HostId        string                 `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	HostName      string                 `protobuf:"bytes,3,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	DpConnected   bool                   `protobuf:"varint,5,opt,name=dp_connected,json=dpConnected,proto3" json:"dp_connected,omitempty"`
	PolicyMode    string                 `protobuf:"bytes,6,opt,name=policy_mode,json=policyMode,proto3" json:"policy_mode,omitempty"`
	Stats         *AgentStats            `protobuf:"bytes,7,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentStatus) Reset() {
	*x = AgentStatus{}
	mi := &file_microseg_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStatus) ProtoMessage() {}

func (x *AgentStatus) ProtoReflect() protoreflect.Message {
	mi := &file_microseg_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStatus.ProtoReflect.Descriptor instead.
func (*AgentStatus) Descriptor() ([]byte, []int) {
	return file_microseg_proto_rawDescGZIP(), []int{8}
}

func (x *AgentStatus) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentStatus) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *AgentStatus) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *AgentStatus) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentStatus) GetDpConnected() bool {
	if x != nil {
		return x.DpConnected
	}
	return false
}

func (x *AgentStatus) GetPolicyMode() string {
	if x != nil {
		return x.PolicyMode
	}
	return ""
}

func (x *AgentStatus) GetStats() *AgentStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type Workload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	HostId        string                 `protobuf:"bytes,3,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	HostName      string                 `protobuf:"bytes,4,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	Domain        string                 `protobuf:"bytes,5,opt,name=domain,proto3" json:"domain,omitempty"`
	Service       string                 `protobuf:"bytes,6,opt,name=service,proto3" json:"service,omitempty"`
	Image         string                 `protobuf:"bytes,7,opt,name=image,proto3" json:"image,omitempty"`
	PolicyMode    string                 `protobuf:"bytes,8,opt,name=policy_mode,json=policyMode,proto3" json:"policy_mode,omitempty"`
	Running       bool                   `protobuf:"varint,9,opt,name=running,proto3" json:"running,omitempty"`
	Pid           int32                  `protobuf:"varint,10,opt,name=pid,proto3" json:"pid,omitempty"`
	Ifaces        []*NetworkInterface    `protobuf:"bytes,11,rep,name=ifaces,proto3" json:"ifaces,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,12,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workload) Reset() {
	*x = Workload{}
	mi := &file_microseg_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workload) ProtoMessage() {}

func (x *Workload) ProtoReflect() protoreflect.Message {
	mi := &file_microseg_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workload.ProtoReflect.Descriptor instead.
func (*Workload) Descriptor() ([]byte, []int) {
	return file_microseg_proto_rawDescGZIP(), []int{9}
}

func (x *Workload) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Workload) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Workload) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *Workload) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *Workload) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Workload) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Workload) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Workload) GetPolicyMode() string {
	if x != nil {
		return x.PolicyMode
	}
	return ""
}

func (x *Workload) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *Workload) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Workload) GetIfaces() []*NetworkInterface {
	if x != nil {
		return x.Ifaces
	}
	return nil
}

func (x *Workload) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type NetworkInterface struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Mac           string                 `protobuf:"bytes,2,opt,name=mac,proto3" json:"mac,omitempty"`
	Addrs         []*IPAddress           `protobuf:"bytes,3,rep,name=addrs,proto3" json:"addrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkInterface) Reset() {
	*x = NetworkInterface{}
	mi := &file_microseg_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkInterface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkInterface) ProtoMessage() {}

func (x *NetworkInterface) ProtoReflect() protoreflect.Message {
	mi := &file_microseg_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkInterface.ProtoReflect.Descriptor instead.
func (*NetworkInterface) Descriptor() ([]byte, []int) {
	return file_microseg_proto_rawDescGZIP(), []int{10}
}

func (x *NetworkInterface) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkInterface) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *NetworkInterface) GetAddrs() []*IPAddress {
	if x != nil {
		return x.Addrs
	}
	return nil
}

type IPAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Scope         string                 `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	Gateway       string                 `protobuf:"bytes,3,opt,name=gateway,proto3" json:"gateway,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPAddress) Reset() {
	*x = IPAddress{}
	mi := &file_microseg_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPAddress) ProtoMessage() {}

func (x *IPAddress) ProtoReflect() protoreflect.Message {
	mi := &file_microseg_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPAddress.ProtoReflect.Descriptor instead.
func (*IPAddress) Descriptor() ([]byte, []int) {
	return file_microseg_proto_rawDescGZIP(), []int{11}
}

func (x *IPAddress) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *IPAddress) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *IPAddress) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

type WorkloadList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workloads     []*Workload            `protobuf:"bytes,1,rep,name=workloads,proto3" json:"workloads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadList) Reset() {
	*x = WorkloadList{}
	mi := &file_microseg_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadList) ProtoMessage() {}

func (x *WorkloadList) ProtoReflect() protoreflect.Message {
	mi := &file_microseg_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadList.ProtoReflect.Descriptor instead.
func (*WorkloadList) Descriptor() ([]byte, []int) {
	return file_microseg_proto_rawDescGZIP(), []int{12}
}

func (x *WorkloadList) GetWorkloads() []*Workload {
	if x != nil {
		return x.Workloads
	}
	return nil
}

type WorkloadEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // add, update, delete
	Workload      *Workload              `protobuf:"bytes,3,opt,name=workload,proto3" json:"workload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadEvent) Reset() {
	*x = WorkloadEvent{}
	mi := &file_microseg_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadEvent) ProtoMessage() {}

func (x *WorkloadEvent) ProtoReflect() protoreflect.Message {
	mi := &file_microseg_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadEvent.ProtoReflect.Descriptor instead.
func (*WorkloadEvent) Descriptor() ([]byte, []int) {
	return file_microseg_proto_rawDescGZIP(), []int{13}
}

func (x *WorkloadEvent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *WorkloadEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *WorkloadEvent) GetWorkload() *Workload {
	if x != nil {
		return x.Workload
	}
	return nil
}

type Connection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientWl      string                 `protobuf:"bytes,1,opt,name=client_wl,json=clientWl,proto3" json:"client_wl,omitempty"`
	ServerWl      string                 `protobuf:"bytes,2,opt,name=server_wl,json=serverWl,proto3" json:"server_wl,omitempty"`
	ClientIp      []byte                 `protobuf:"bytes,3,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	ServerIp      []byte                 `protobuf:"bytes,4,opt,name=server_ip,json=serverIp,proto3" json:"server_ip,omitempty"`
	ClientPort    uint32                 `protobuf:"varint,5,opt,name=client_port,json=clientPort,proto3" json:"client_port,omitempty"`
	ServerPort    uint32                 `protobuf:"varint,6,opt,name=server_port,json=serverPort,proto3" json:"server_port,omitempty"`
	IpProto       uint32                 `protobuf:"varint,7,opt,name=ip_proto,json=ipProto,proto3" json:"ip_proto,omitempty"`
	Application   uint32                 `protobuf:"varint,8,opt,name=application,proto3" json:"application,omitempty"`
	Bytes         uint64                 `protobuf:"varint,9,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Sessions      uint32                 `protobuf:"varint,10,opt,name=sessions,proto3" json:"sessions,omitempty"`
	FirstSeenAt   uint32                 `protobuf:"varint,11,opt,name=first_seen_at,json=firstSeenAt,proto3" json:"first_seen_at,omitempty"`
	LastSeenAt    uint32                 `protobuf:"varint,12,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	ThreatId      uint32                 `protobuf:"varint,13,opt,name=threat_id,json=threatId,proto3" json:"threat_id,omitempty"`
	Severity      uint32                 `protobuf:"varint,14,opt,name=severity,proto3" json:"severity,omitempty"`
	PolicyAction  uint32                 `protobuf:"varint,15,opt,name=policy_action,json=policyAction,proto3" json:"policy_action,omitempty"`
	PolicyId      uint32                 `protobuf:"varint,16,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	Ingress       bool                   `protobuf:"varint,17,opt,name=ingress,proto3" json:"ingress,omitempty"`
	ExternalPeer  bool                   `protobuf:"varint,18,opt,name=external_peer,json=externalPeer,proto3" json:"external_peer,omitempty"`
	LocalPeer     bool                   `protobuf:"varint,19,opt,name=local_peer,json=localPeer,proto3" json:"local_peer,omitempty"`
	Scope         string                 `protobuf:"bytes,20,opt,name=scope,proto3" json:"scope,omitempty"`
	Network       string                 `protobuf:"bytes,21,opt,name=network,proto3" json:"network,omitempty"`
	Violates      uint32                 `protobuf:"varint,22,opt,name=violates,proto3" json:"violates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Connection) Reset() {
	*x = Connection{}
	mi := &file_microseg_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Connection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connection) ProtoMessage() {}

func (x *Connection) ProtoReflect() protoreflect.Message {
	mi := &file_microseg_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connection.ProtoReflect.Descriptor instead.
func (*Connection) Descriptor() ([]byte, []int) {
	return file_microseg_proto_rawDescGZIP(), []int{14}
}

func (x *Connection) GetClientWl() string {
	if x != nil {
		return x.ClientWl
	}
	return ""
}

func (x *Connection) GetServerWl() string {
	if x != nil {
		return x.ServerWl
	}
	return ""
}

func (x *Connection) GetClientIp() []byte {
	if x != nil {
		return x.ClientIp
	}
	return nil
}

func (x *Connection) GetServerIp() []byte {
	if x != nil {
		return x.ServerIp
	}
	return nil
}

func (x *Connection) GetClientPort() uint32 {
	if x != nil {
		return x.ClientPort
	}
	return 0
}

func (x *Connection) GetServerPort() uint32 {
	if x != nil {
		return x.ServerPort
	}
	return 0
}

func (x *Connection) GetIpProto() uint32 {
	if x != nil {
		return x.IpProto
	}
	return 0
}

func (x *Connection) GetApplication() uint32 {
	if x != nil {
		return x.Application
	}
	return 0
}

func (x *Connection) GetBytes() uint64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

func (x *Connection) GetSessions() uint32 {
	if x != nil {
		return x.Sessions
	}
	return 0
}

func (x *Connection) GetFirstSeenAt() uint32 {
	if x != nil {
		return x.FirstSeenAt
	}
	return 0
}

func (x *Connection) GetLastSeenAt() uint32 {
	if x != nil {
		return x.LastSeenAt
	}
	return 0
}

func (x *Connection) GetThreatId() uint32 {
	if x != nil {
		return x.ThreatId
	}
	return 0
}

func (x *Connection) GetSeverity() uint32 {
	if x != nil {
		return x.Severity
	}
	return 0
}

func (x *Connection) GetPolicyAction() uint32 {
	if x != nil {
		return x.PolicyAction
	}
	return 0
}

func (x *Connection) GetPolicyId() uint32 {
	if x != nil {
		return x.PolicyId
	}
	return 0
}

func (x *Connection) GetIngress() bool {
	if x != nil {
		return x.Ingress
	}
	return false
}

func (x *Connection) GetExternalPeer() bool {
	if x != nil {
		return x.ExternalPeer
	}
	return false
}

func (x *Connection) GetLocalPeer() bool {
	if x != nil {
		return x.LocalPeer
	}
	return false
}

func (x *Connection) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *Connection) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Connection) GetViolates() uint32 {
	if x != nil {
		return x.Violates
	}
	return 0
}

type ConnectionReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	HostId        string                 `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Connections   []*Connection          `protobuf:"bytes,3,rep,name=connections,proto3" json:"connections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionReport) Reset() {
	*x = ConnectionReport{}
	mi := &file_microseg_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionReport) ProtoMessage() {}

func (x *ConnectionReport) ProtoReflect() protoreflect.Message {
	mi := &file_microseg_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionReport.ProtoReflect.Descriptor instead.
func (*ConnectionReport) Descriptor() ([]byte, []int) {
	return file_microseg_proto_rawDescGZIP(), []int{15}
}

func (x *ConnectionReport) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ConnectionReport) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *ConnectionReport) GetConnections() []*Connection {
	if x != nil {
		return x.Connections
	}
	return nil
}

type ThreatLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ThreatId      uint32                 `protobuf:"varint,2,opt,name=threat_id,json=threatId,proto3" json:"threat_id,omitempty"`
	ThreatName    string                 `protobuf:"bytes,3,opt,name=threat_name,json=threatName,proto3" json:"threat_name,omitempty"`
	Severity      string                 `protobuf:"bytes,4,opt,name=severity,proto3" json:"severity,omitempty"`
	ClientWl      string                 `protobuf:"bytes,5,opt,name=client_wl,json=clientWl,proto3" json:"client_wl,omitempty"`
	ServerWl      string                 `protobuf:"bytes,6,opt,name=server_wl,json=serverWl,proto3" json:"server_wl,omitempty"`
	ClientIp      []byte                 `protobuf:"bytes,7,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	ServerIp      []byte                 `protobuf:"bytes,8,opt,name=server_ip,json=serverIp,proto3" json:"server_ip,omitempty"`
	ServerPort    uint32                 `protobuf:"varint,9,opt,name=server_port,json=serverPort,proto3" json:"server_port,omitempty"`
	IpProto       uint32                 `protobuf:"varint,10,opt,name=ip_proto,json=ipProto,proto3" json:"ip_proto,omitempty"`
	PktIngress    bool                   `protobuf:"varint,11,opt,name=pkt_ingress,json=pktIngress,proto3" json:"pkt_ingress,omitempty"`
	LocalPeer     bool                   `protobuf:"varint,12,opt,name=local_peer,json=localPeer,proto3" json:"local_peer,omitempty"`
	ReportedAt    uint64                 `protobuf:"varint,13,opt,name=reported_at,json=reportedAt,proto3" json:"reported_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreatLog) Reset() {
	*x = ThreatLog{}
	mi := &file_microseg_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreatLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreatLog) ProtoMessage() {}

func (x *ThreatLog) ProtoReflect() protoreflect.Message {
	mi := &file_microseg_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreatLog.ProtoReflect.Descriptor instead.
func (*ThreatLog) Descriptor() ([]byte, []int) {
	return file_microseg_proto_rawDescGZIP(), []int{16}
}

func (x *ThreatLog) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ThreatLog) GetThreatId() uint32 {
	if x != nil {
		return x.ThreatId
	}
	return 0
}

func (x *ThreatLog) GetThreatName() string {
	if x != nil {
		return x.ThreatName
	}
	return ""
}

func (x *ThreatLog) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *ThreatLog) GetClientWl() string {
	if x != nil {
		return x.ClientWl
	}
	return ""
}

func (x *ThreatLog) GetServerWl() string {
	if x != nil {
		return x.ServerWl
	}
	return ""
}

func (x *ThreatLog) GetClientIp() []byte {
	if x != nil {
		return x.ClientIp
	}
	return nil
}

func (x *ThreatLog) GetServerIp() []byte {
	if x != nil {
		return x.ServerIp
	}
	return nil
}

func (x *ThreatLog) GetServerPort() uint32 {
	if x != nil {
		return x.ServerPort
	}
	return 0
}

func (x *ThreatLog) GetIpProto() uint32 {
	if x != nil {
		return x.IpProto
	}
	return 0
}

func (x *ThreatLog) GetPktIngress() bool {
	if x != nil {
		return x.PktIngress
	}
	return false
}

func (x *ThreatLog) GetLocalPeer() bool {
	if x != nil {
		return x.LocalPeer
	}
	return false
}

func (x *ThreatLog) GetReportedAt() uint64 {
	if x != nil {
		return x.ReportedAt
	}
	return 0
}

type ThreatReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	HostId        string                 `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Threats       []*ThreatLog           `protobuf:"bytes,3,rep,name=threats,proto3" json:"threats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreatReport) Reset() {
	*x = ThreatReport{}
	mi := &file_microseg_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreatReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreatReport) ProtoMessage() {}

func (x *ThreatReport) ProtoReflect() protoreflect.Message {
	mi := &file_microseg_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreatReport.ProtoReflect.Descriptor instead.
func (*ThreatReport) Descriptor() ([]byte, []int) {
	return file_microseg_proto_rawDescGZIP(), []int{17}
}

func (x *ThreatReport) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ThreatReport) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *ThreatReport) GetThreats() []*ThreatLog {
	if x != nil {
		return x.Threats
	}
	return nil
}

type PolicyRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Ports         string                 `protobuf:"bytes,4,opt,name=ports,proto3" json:"ports,omitempty"`
	Applications  []uint32               `protobuf:"varint,5,rep,packed,name=applications,proto3" json:"applications,omitempty"`
	Action        uint32                 `protobuf:"varint,6,opt,name=action,proto3" json:"action,omitempty"` // 0=open, 1=allow, 2=deny, 3=violate
	Ingress       bool                   `protobuf:"varint,7,opt,name=ingress,proto3" json:"ingress,omitempty"`
	Priority      uint32                 `protobuf:"varint,8,opt,name=priority,proto3" json:"priority,omitempty"`
	Disable       bool                   `protobuf:"varint,9,opt,name=disable,proto3" json:"disable,omitempty"`
	Comment       string                 `protobuf:"bytes,10,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyRule) Reset() {
	*x = PolicyRule{}
	mi := &file_microseg_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyRule) ProtoMessage() {}

func (x *PolicyRule) ProtoReflect() protoreflect.Message {
	mi := &file_microseg_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyRule.ProtoReflect.Descriptor instead.
func (*PolicyRule) Descriptor() ([]byte, []int) {
	return file_microseg_proto_rawDescGZIP(), []int{18}
}

func (x *PolicyRule) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PolicyRule) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *PolicyRule) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *PolicyRule) GetPorts() string {
	if x != nil {
		return x.Ports
	}
	return ""
}

func (x *PolicyRule) GetApplications() []uint32 {
	if x != nil {
		return x.Applications
	}
	return nil
}

func (x *PolicyRule) GetAction() uint32 {
	if x != nil {
		return x.Action
	}
	return 0
}

func (x *PolicyRule) GetIngress() bool {
	if x != nil {
		return x.Ingress
	}
	return false
}

func (x *PolicyRule) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *PolicyRule) GetDisable() bool {
	if x != nil {
		return x.Disable
	}
	return false
}

func (x *PolicyRule) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type IPRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SrcIp         []byte                 `protobuf:"bytes,2,opt,name=src_ip,json=srcIp,proto3" json:"src_ip,omitempty"`
	DstIp         []byte                 `protobuf:"bytes,3,opt,name=dst_ip,json=dstIp,proto3" json:"dst_ip,omitempty"`
	SrcMask       []byte                 `protobuf:"bytes,4,opt,name=src_mask,json=srcMask,proto3" json:"src_mask,omitempty"`
	DstMask       []byte                 `protobuf:"bytes,5,opt,name=dst_mask,json=dstMask,proto3" json:"dst_mask,omitempty"`
	Port          uint32                 `protobuf:"varint,6,opt,name=port,proto3" json:"port,omitempty"`
	PortR         uint32                 `protobuf:"varint,7,opt,name=port_r,json=portR,proto3" json:"port_r,omitempty"`
	IpProto       uint32                 `protobuf:"varint,8,opt,name=ip_proto,json=ipProto,proto3" json:"ip_proto,omitempty"`
	Action        uint32                 `protobuf:"varint,9,opt,name=action,proto3" json:"action,omitempty"`
	Ingress       bool                   `protobuf:"varint,10,opt,name=ingress,proto3" json:"ingress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPRule) Reset() {
	*x = IPRule{}
	mi := &file_microseg_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPRule) ProtoMessage() {}

func (x *IPRule) ProtoReflect() protoreflect.Message {
	mi := &file_microseg_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPRule.ProtoReflect.Descriptor instead.
func (*IPRule) Descriptor() ([]byte, []int) {
	return file_microseg_proto_rawDescGZIP(), []int{19}
}

func (x *IPRule) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *IPRule) GetSrcIp() []byte {
	if x != nil {
		return x.SrcIp
	}
	return nil
}

func (x *IPRule) GetDstIp() []byte {
	if x != nil {
		return x.DstIp
	}
	return nil
}

func (x *IPRule) GetSrcMask() []byte {
	if x != nil {
		return x.SrcMask
	}
	return nil
}

func (x *IPRule) GetDstMask() []byte {
	if x != nil {
		return x.DstMask
	}
	return nil
}

func (x *IPRule) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *IPRule) GetPortR() uint32 {
	if x != nil {
		return x.PortR
	}
	return 0
}

func (x *IPRule) GetIpProto() uint32 {
	if x != nil {
		return x.IpProto
	}
	return 0
}

func (x *IPRule) GetAction() uint32 {
	if x != nil {
		return x.Action
	}
	return 0
}

func (x *IPRule) GetIngress() bool {
	if x != nil {
		return x.Ingress
	}
	return false
}

type PolicyConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkloadId    string                 `protobuf:"bytes,1,opt,name=workload_id,json=workloadId,proto3" json:"workload_id,omitempty"`
	Macs          []string               `protobuf:"bytes,2,rep,name=macs,proto3" json:"macs,omitempty"`
	Mode          string                 `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	DefAction     uint32                 `protobuf:"varint,4,opt,name=def_action,json=defAction,proto3" json:"def_action,omitempty"`
	ApplyDir      int32                  `protobuf:"varint,5,opt,name=apply_dir,json=applyDir,proto3" json:"apply_dir,omitempty"`
	Rules         []*IPRule              `protobuf:"bytes,6,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyConfig) Reset() {
	*x = PolicyConfig{}
	mi := &file_microseg_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyConfig) ProtoMessage() {}

func (x *PolicyConfig) ProtoReflect() protoreflect.Message {
	mi := &file_microseg_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyConfig.ProtoReflect.Descriptor instead.
func (*PolicyConfig) Descriptor() ([]byte, []int) {
	return file_microseg_proto_rawDescGZIP(), []int{20}
}

func (x *PolicyConfig) GetWorkloadId() string {
	if x != nil {
		return x.WorkloadId
	}
	return ""
}

func (x *PolicyConfig) GetMacs() []string {
	if x != nil {
		return x.Macs
	}
	return nil
}

func (x *PolicyConfig) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *PolicyConfig) GetDefAction() uint32 {
	if x != nil {
		return x.DefAction
	}
	return 0
}

func (x *PolicyConfig) GetApplyDir() int32 {
	if x != nil {
		return x.ApplyDir
	}
	return 0
}

func (x *PolicyConfig) GetRules() []*IPRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type PolicyList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*PolicyRule          `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyList) Reset() {
	*x = PolicyList{}
	mi := &file_microseg_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyList) ProtoMessage() {}

func (x *PolicyList) ProtoReflect() protoreflect.Message {
	mi := &file_microseg_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyList.ProtoReflect.Descriptor instead.
func (*PolicyList) Descriptor() ([]byte, []int) {
	return file_microseg_proto_rawDescGZIP(), []int{21}
}

func (x *PolicyList) GetRules() []*PolicyRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type PolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	WorkloadIds   []string               `protobuf:"bytes,2,rep,name=workload_ids,json=workloadIds,proto3" json:"workload_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyRequest) Reset() {
	*x = PolicyRequest{}
	mi := &file_microseg_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyRequest) ProtoMessage() {}

func (x *PolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_microseg_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyRequest.ProtoReflect.Descriptor instead.
func (*PolicyRequest) Descriptor() ([]byte, []int) {
	return file_microseg_proto_rawDescGZIP(), []int{22}
}

func (x *PolicyRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *PolicyRequest) GetWorkloadIds() []string {
	if x != nil {
		return x.WorkloadIds
	}
	return nil
}

type GroupModeConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupName     string                 `protobuf:"bytes,1,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	Mode          string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"` // Monitor, Protect
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupModeConfig) Reset() {
	*x = GroupModeConfig{}
	mi := &file_microseg_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupModeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupModeConfig) ProtoMessage() {}

func (x *GroupModeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_microseg_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupModeConfig.ProtoReflect.Descriptor instead.
func (*GroupModeConfig) Descriptor() ([]byte, []int) {
	return file_microseg_proto_rawDescGZIP(), []int{23}
}

func (x *GroupModeConfig) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *GroupModeConfig) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type Subnet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            []byte                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Mask          []byte                 `protobuf:"bytes,2,opt,name=mask,proto3" json:"mask,omitempty"`
	Scope         string                 `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subnet) Reset() {
	*x = Subnet{}
	mi := &file_microseg_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subnet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subnet) ProtoMessage() {}

func (x *Subnet) ProtoReflect() protoreflect.Message {
	mi := &file_microseg_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subnet.ProtoReflect.Descriptor instead.
func (*Subnet) Descriptor() ([]byte, []int) {
	return file_microseg_proto_rawDescGZIP(), []int{24}
}

func (x *Subnet) GetIp() []byte {
	if x != nil {
		return x.Ip
	}
	return nil
}

func (x *Subnet) GetMask() []byte {
	if x != nil {
		return x.Mask
	}
	return nil
}

func (x *Subnet) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

type SubnetConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subnets       []*Subnet              `protobuf:"bytes,1,rep,name=subnets,proto3" json:"subnets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubnetConfig) Reset() {
	*x = SubnetConfig{}
	mi := &file_microseg_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubnetConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubnetConfig) ProtoMessage() {}

func (x *SubnetConfig) ProtoReflect() protoreflect.Message {
	mi := &file_microseg_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubnetConfig.ProtoReflect.Descriptor instead.
func (*SubnetConfig) Descriptor() ([]byte, []int) {
	return file_microseg_proto_rawDescGZIP(), []int{25}
}

func (x *SubnetConfig) GetSubnets() []*Subnet {
	if x != nil {
		return x.Subnets
	}
	return nil
}

var File_microseg_proto protoreflect.FileDescriptor

const file_microseg_proto_rawDesc = "" +
	"\n" +
	"\x0emicroseg.proto\x12\bmicroseg\"\a\n" +
	"\x05Empty\">\n" +
	"\x0eConfigResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"g\n" +
	"\x0eReportResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x0freport_interval\x18\x03 \x01(\rR\x0ereportInterval\"\x92\x01\n" +
	"\tAgentInfo\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x17\n" +
	"\ahost_id\x18\x02 \x01(\tR\x06hostId\x12\x1b\n" +
	"\thost_name\x18\x03 \x01(\tR\bhostName\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x1a\n" +
	"\bplatform\x18\x05 \x01(\tR\bplatform\"\x88\x01\n" +
	"\x10RegisterResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x03 \x01(\tR\tclusterId\x12'\n" +
	"\x0freport_interval\x18\x04 \x01(\rR\x0ereportInterval\"w\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x04R\ttimestamp\x12*\n" +
	"\x05stats\x18\x03 \x01(\v2\x14.microseg.AgentStatsR\x05stats\"E\n" +
	"\x11HeartbeatResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x04R\ttimestamp\"\xc1\x01\n" +
	"\n" +
	"AgentStats\x12%\n" +
	"\x0eworkload_count\x18\x01 \x01(\rR\rworkloadCount\x12)\n" +
	"\x10connection_count\x18\x02 \x01(\rR\x0fconnectionCount\x12!\n" +
	"\fpolicy_count\x18\x03 \x01(\rR\vpolicyCount\x12!\n" +
	"\fmemory_usage\x18\x04 \x01(\x04R\vmemoryUsage\x12\x1b\n" +
	"\tcpu_usage\x18\x05 \x01(\x02R\bcpuUsage\"\xe8\x01\n" +
	"\vAgentStatus\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x17\n" +
	"\ahost_id\x18\x02 \x01(\tR\x06hostId\x12\x1b\n" +
	"\thost_name\x18\x03 \x01(\tR\bhostName\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12!\n" +
	"\fdp_connected\x18\x05 \x01(\bR\vdpConnected\x12\x1f\n" +
	"\vpolicy_mode\x18\x06 \x01(\tR\n" +
	"policyMode\x12*\n" +
	"\x05stats\x18\a \x01(\v2\x14.microseg.AgentStatsR\x05stats\"\xa0\x03\n" +
	"\bWorkload\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\ahost_id\x18\x03 \x01(\tR\x06hostId\x12\x1b\n" +
	"\thost_name\x18\x04 \x01(\tR\bhostName\x12\x16\n" +
	"\x06domain\x18\x05 \x01(\tR\x06domain\x12\x18\n" +
	"\aservice\x18\x06 \x01(\tR\aservice\x12\x14\n" +
	"\x05image\x18\a \x01(\tR\x05image\x12\x1f\n" +
	"\vpolicy_mode\x18\b \x01(\tR\n" +
	"policyMode\x12\x18\n" +
	"\arunning\x18\t \x01(\bR\arunning\x12\x10\n" +
	"\x03pid\x18\n" +
	" \x01(\x05R\x03pid\x122\n" +
	"\x06ifaces\x18\v \x03(\v2\x1a.microseg.NetworkInterfaceR\x06ifaces\x126\n" +
	"\x06labels\x18\f \x03(\v2\x1e.microseg.Workload.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"c\n" +
	"\x10NetworkInterface\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03mac\x18\x02 \x01(\tR\x03mac\x12)\n" +
	"\x05addrs\x18\x03 \x03(\v2\x13.microseg.IPAddressR\x05addrs\"K\n" +
	"\tIPAddress\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x14\n" +
	"\x05scope\x18\x02 \x01(\tR\x05scope\x12\x18\n" +
	"\agateway\x18\x03 \x01(\tR\agateway\"@\n" +
	"\fWorkloadList\x120\n" +
	"\tworkloads\x18\x01 \x03(\v2\x12.microseg.WorkloadR\tworkloads\"y\n" +
	"\rWorkloadEvent\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12.\n" +
	"\bworkload\x18\x03 \x01(\v2\x12.microseg.WorkloadR\bworkload\"\x9c\x05\n" +
	"\n" +
	"Connection\x12\x1b\n" +
	"\tclient_wl\x18\x01 \x01(\tR\bclientWl\x12\x1b\n" +
	"\tserver_wl\x18\x02 \x01(\tR\bserverWl\x12\x1b\n" +
	"\tclient_ip\x18\x03 \x01(\fR\bclientIp\x12\x1b\n" +
	"\tserver_ip\x18\x04 \x01(\fR\bserverIp\x12\x1f\n" +
	"\vclient_port\x18\x05 \x01(\rR\n" +
	"clientPort\x12\x1f\n" +
	"\vserver_port\x18\x06 \x01(\rR\n" +
	"serverPort\x12\x19\n" +
	"\bip_proto\x18\a \x01(\rR\aipProto\x12 \n" +
	"\vapplication\x18\b \x01(\rR\vapplication\x12\x14\n" +
	"\x05bytes\x18\t \x01(\x04R\x05bytes\x12\x1a\n" +
	"\bsessions\x18\n" +
	" \x01(\rR\bsessions\x12\"\n" +
	"\rfirst_seen_at\x18\v \x01(\rR\vfirstSeenAt\x12 \n" +
	"\flast_seen_at\x18\f \x01(\rR\n" +
	"lastSeenAt\x12\x1b\n" +
	"\tthreat_id\x18\r \x01(\rR\bthreatId\x12\x1a\n" +
	"\bseverity\x18\x0e \x01(\rR\bseverity\x12#\n" +
	"\rpolicy_action\x18\x0f \x01(\rR\fpolicyAction\x12\x1b\n" +
	"\tpolicy_id\x18\x10 \x01(\rR\bpolicyId\x12\x18\n" +
	"\aingress\x18\x11 \x01(\bR\aingress\x12#\n" +
	"\rexternal_peer\x18\x12 \x01(\bR\fexternalPeer\x12\x1d\n" +
	"\n" +
	"local_peer\x18\x13 \x01(\bR\tlocalPeer\x12\x14\n" +
	"\x05scope\x18\x14 \x01(\tR\x05scope\x12\x18\n" +
	"\anetwork\x18\x15 \x01(\tR\anetwork\x12\x1a\n" +
	"\bviolates\x18\x16 \x01(\rR\bviolates\"~\n" +
	"\x10ConnectionReport\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x17\n" +
	"\ahost_id\x18\x02 \x01(\tR\x06hostId\x126\n" +
	"\vconnections\x18\x03 \x03(\v2\x14.microseg.ConnectionR\vconnections\"\x86\x03\n" +
	"\tThreatLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tthreat_id\x18\x02 \x01(\rR\bthreatId\x12\x1f\n" +
	"\vthreat_name\x18\x03 \x01(\tR\n" +
	"threatName\x12\x1a\n" +
	"\bseverity\x18\x04 \x01(\tR\bseverity\x12\x1b\n" +
	"\tclient_wl\x18\x05 \x01(\tR\bclientWl\x12\x1b\n" +
	"\tserver_wl\x18\x06 \x01(\tR\bserverWl\x12\x1b\n" +
	"\tclient_ip\x18\a \x01(\fR\bclientIp\x12\x1b\n" +
	"\tserver_ip\x18\b \x01(\fR\bserverIp\x12\x1f\n" +
	"\vserver_port\x18\t \x01(\rR\n" +
	"serverPort\x12\x19\n" +
	"\bip_proto\x18\n" +
	" \x01(\rR\aipProto\x12\x1f\n" +
	"\vpkt_ingress\x18\v \x01(\bR\n" +
	"pktIngress\x12\x1d\n" +
	"\n" +
	"local_peer\x18\f \x01(\bR\tlocalPeer\x12\x1f\n" +
	"\vreported_at\x18\r \x01(\x04R\n" +
	"reportedAt\"q\n" +
	"\fThreatReport\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x17\n" +
	"\ahost_id\x18\x02 \x01(\tR\x06hostId\x12-\n" +
	"\athreats\x18\x03 \x03(\v2\x13.microseg.ThreatLogR\athreats\"\xfc\x01\n" +
	"\n" +
	"PolicyRule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\x12\x14\n" +
	"\x05ports\x18\x04 \x01(\tR\x05ports\x12\"\n" +
	"\fapplications\x18\x05 \x03(\rR\fapplications\x12\x16\n" +
	"\x06action\x18\x06 \x01(\rR\x06action\x12\x18\n" +
	"\aingress\x18\a \x01(\bR\aingress\x12\x1a\n" +
	"\bpriority\x18\b \x01(\rR\bpriority\x12\x18\n" +
	"\adisable\x18\t \x01(\bR\adisable\x12\x18\n" +
	"\acomment\x18\n" +
	" \x01(\tR\acomment\"\xf4\x01\n" +
	"\x06IPRule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x15\n" +
	"\x06src_ip\x18\x02 \x01(\fR\x05srcIp\x12\x15\n" +
	"\x06dst_ip\x18\x03 \x01(\fR\x05dstIp\x12\x19\n" +
	"\bsrc_mask\x18\x04 \x01(\fR\asrcMask\x12\x19\n" +
	"\bdst_mask\x18\x05 \x01(\fR\adstMask\x12\x12\n" +
	"\x04port\x18\x06 \x01(\rR\x04port\x12\x15\n" +
	"\x06port_r\x18\a \x01(\rR\x05portR\x12\x19\n" +
	"\bip_proto\x18\b \x01(\rR\aipProto\x12\x16\n" +
	"\x06action\x18\t \x01(\rR\x06action\x12\x18\n" +
	"\aingress\x18\n" +
	" \x01(\bR\aingress\"\xbb\x01\n" +
	"\fPolicyConfig\x12\x1f\n" +
	"\vworkload_id\x18\x01 \x01(\tR\n" +
	"workloadId\x12\x12\n" +
	"\x04macs\x18\x02 \x03(\tR\x04macs\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\x12\x1d\n" +
	"\n" +
	"def_action\x18\x04 \x01(\rR\tdefAction\x12\x1b\n" +
	"\tapply_dir\x18\x05 \x01(\x05R\bapplyDir\x12&\n" +
	"\x05rules\x18\x06 \x03(\v2\x10.microseg.IPRuleR\x05rules\"8\n" +
	"\n" +
	"PolicyList\x12*\n" +
	"\x05rules\x18\x01 \x03(\v2\x14.microseg.PolicyRuleR\x05rules\"M\n" +
	"\rPolicyRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12!\n" +
	"\fworkload_ids\x18\x02 \x03(\tR\vworkloadIds\"D\n" +
	"\x0fGroupModeConfig\x12\x1d\n" +
	"\n" +
	"group_name\x18\x01 \x01(\tR\tgroupName\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\"B\n" +
	"\x06Subnet\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\fR\x02ip\x12\x12\n" +
	"\x04mask\x18\x02 \x01(\fR\x04mask\x12\x14\n" +
	"\x05scope\x18\x03 \x01(\tR\x05scope\":\n" +
	"\fSubnetConfig\x12*\n" +
	"\asubnets\x18\x01 \x03(\v2\x10.microseg.SubnetR\asubnets2\xc9\x02\n" +
	"\fAgentService\x12@\n" +
	"\fConfigPolicy\x12\x16.microseg.PolicyConfig\x1a\x18.microseg.ConfigResponse\x12F\n" +
	"\x0fConfigGroupMode\x12\x19.microseg.GroupModeConfig\x1a\x18.microseg.ConfigResponse\x12A\n" +
	"\rConfigSubnets\x12\x16.microseg.SubnetConfig\x1a\x18.microseg.ConfigResponse\x123\n" +
	"\tGetStatus\x12\x0f.microseg.Empty\x1a\x15.microseg.AgentStatus\x127\n" +
	"\fGetWorkloads\x12\x0f.microseg.Empty\x1a\x16.microseg.WorkloadList2\xa7\x03\n" +
	"\x11ControllerService\x12;\n" +
	"\bRegister\x12\x13.microseg.AgentInfo\x1a\x1a.microseg.RegisterResponse\x12D\n" +
	"\tHeartbeat\x12\x1a.microseg.HeartbeatRequest\x1a\x1b.microseg.HeartbeatResponse\x12I\n" +
	"\x11ReportConnections\x12\x1a.microseg.ConnectionReport\x1a\x18.microseg.ReportResponse\x12A\n" +
	"\rReportThreats\x12\x16.microseg.ThreatReport\x1a\x18.microseg.ReportResponse\x12C\n" +
	"\x0eReportWorkload\x12\x17.microseg.WorkloadEvent\x1a\x18.microseg.ReportResponse\x12<\n" +
	"\vGetPolicies\x12\x17.microseg.PolicyRequest\x1a\x14.microseg.PolicyListB$Z\"github.com/micro-segment/api/protob\x06proto3"

var (
	file_microseg_proto_rawDescOnce sync.Once
	file_microseg_proto_rawDescData []byte
)

func file_microseg_proto_rawDescGZIP() []byte {
	file_microseg_proto_rawDescOnce.Do(func() {
		file_microseg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_microseg_proto_rawDesc), len(file_microseg_proto_rawDesc)))
	})
	return file_microseg_proto_rawDescData
}

var file_microseg_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_microseg_proto_goTypes = []any{
	(*Empty)(nil),             // 0: microseg.Empty
	(*ConfigResponse)(nil),    // 1: microseg.ConfigResponse
	(*ReportResponse)(nil),    // 2: microseg.ReportResponse
	(*AgentInfo)(nil),         // 3: microseg.AgentInfo
	(*RegisterResponse)(nil),  // 4: microseg.RegisterResponse
	(*HeartbeatRequest)(nil),  // 5: microseg.HeartbeatRequest
	(*HeartbeatResponse)(nil), // 6: microseg.HeartbeatResponse
	(*AgentStats)(nil),        // 7: microseg.AgentStats
	(*AgentStatus)(nil),       // 8: microseg.AgentStatus
	(*Workload)(nil),          // 9: microseg.Workload
	(*NetworkInterface)(nil),  // 10: microseg.NetworkInterface
	(*IPAddress)(nil),         // 11: microseg.IPAddress
	(*WorkloadList)(nil),      // 12: microseg.WorkloadList
	(*WorkloadEvent)(nil),     // 13: microseg.WorkloadEvent
	(*Connection)(nil),        // 14: microseg.Connection
	(*ConnectionReport)(nil),  // 15: microseg.ConnectionReport
	(*ThreatLog)(nil),         // 16: microseg.ThreatLog
	(*ThreatReport)(nil),      // 17: microseg.ThreatReport
	(*PolicyRule)(nil),        // 18: microseg.PolicyRule
	(*IPRule)(nil),            // 19: microseg.IPRule
	(*PolicyConfig)(nil),      // 20: microseg.PolicyConfig
	(*PolicyList)(nil),        // 21: microseg.PolicyList
	(*PolicyRequest)(nil),     // 22: microseg.PolicyRequest
	(*GroupModeConfig)(nil),   // 23: microseg.GroupModeConfig
	(*Subnet)(nil),            // 24: microseg.Subnet
	(*SubnetConfig)(nil),      // 25: microseg.SubnetConfig
	nil,                       // 26: microseg.Workload.LabelsEntry
}
var file_microseg_proto_depIdxs = []int32{
	7,  // 0: microseg.HeartbeatRequest.stats:type_name -> microseg.AgentStats
	7,  // 1: microseg.AgentStatus.stats:type_name -> microseg.AgentStats
	10, // 2: microseg.Workload.ifaces:type_name -> microseg.NetworkInterface
	26, // 3: microseg.Workload.labels:type_name -> microseg.Workload.LabelsEntry
	11, // 4: microseg.NetworkInterface.addrs:type_name -> microseg.IPAddress
	9,  // 5: microseg.WorkloadList.workloads:type_name -> microseg.Workload
	9,  // 6: microseg.WorkloadEvent.workload:type_name -> microseg.Workload
	14, // 7: microseg.ConnectionReport.connections:type_name -> microseg.Connection
	16, // 8: microseg.ThreatReport.threats:type_name -> microseg.ThreatLog
	19, // 9: microseg.PolicyConfig.rules:type_name -> microseg.IPRule
	18, // 10: microseg.PolicyList.rules:type_name -> microseg.PolicyRule
	24, // 11: microseg.SubnetConfig.subnets:type_name -> microseg.Subnet
	20, // 12: microseg.AgentService.ConfigPolicy:input_type -> microseg.PolicyConfig
	23, // 13: microseg.AgentService.ConfigGroupMode:input_type -> microseg.GroupModeConfig
	25, // 14: microseg.AgentService.ConfigSubnets:input_type -> microseg.SubnetConfig
	0,  // 15: microseg.AgentService.GetStatus:input_type -> microseg.Empty
	0,  // 16: microseg.AgentService.GetWorkloads:input_type -> microseg.Empty
	3,  // 17: microseg.ControllerService.Register:input_type -> microseg.AgentInfo
	5,  // 18: microseg.ControllerService.Heartbeat:input_type -> microseg.HeartbeatRequest
	15, // 19: microseg.ControllerService.ReportConnections:input_type -> microseg.ConnectionReport
	17, // 20: microseg.ControllerService.ReportThreats:input_type -> microseg.ThreatReport
	13, // 21: microseg.ControllerService.ReportWorkload:input_type -> microseg.WorkloadEvent
	22, // 22: microseg.ControllerService.GetPolicies:input_type -> microseg.PolicyRequest
	1,  // 23: microseg.AgentService.ConfigPolicy:output_type -> microseg.ConfigResponse
	1,  // 24: microseg.AgentService.ConfigGroupMode:output_type -> microseg.ConfigResponse
	1,  // 25: microseg.AgentService.ConfigSubnets:output_type -> microseg.ConfigResponse
	8,  // 26: microseg.AgentService.GetStatus:output_type -> microseg.AgentStatus
	12, // 27: microseg.AgentService.GetWorkloads:output_type -> microseg.WorkloadList
	4,  // 28: microseg.ControllerService.Register:output_type -> microseg.RegisterResponse
	6,  // 29: microseg.ControllerService.Heartbeat:output_type -> microseg.HeartbeatResponse
	2,  // 30: microseg.ControllerService.ReportConnections:output_type -> microseg.ReportResponse
	2,  // 31: microseg.ControllerService.ReportThreats:output_type -> microseg.ReportResponse
	2,  // 32: microseg.ControllerService.ReportWorkload:output_type -> microseg.ReportResponse
	21, // 33: microseg.ControllerService.GetPolicies:output_type -> microseg.PolicyList
	23, // [23:34] is the sub-list for method output_type
	12, // [12:23] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_microseg_proto_init() }
func file_microseg_proto_init() {
	if File_microseg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_microseg_proto_rawDesc), len(file_microseg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_microseg_proto_goTypes,
		DependencyIndexes: file_microseg_proto_depIdxs,
		MessageInfos:      file_microseg_proto_msgTypes,
	}.Build()
	File_microseg_proto = out.File
	file_microseg_proto_goTypes = nil
	file_microseg_proto_depIdxs = nil
}
