// 微隔离 gRPC 协议定义
// Agent <-> Controller 通信协议

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.19.5
// source: microseg.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_ConfigPolicy_FullMethodName    = "/microseg.AgentService/ConfigPolicy"
	AgentService_ConfigGroupMode_FullMethodName = "/microseg.AgentService/ConfigGroupMode"
	AgentService_ConfigSubnets_FullMethodName   = "/microseg.AgentService/ConfigSubnets"
	AgentService_GetStatus_FullMethodName       = "/microseg.AgentService/GetStatus"
	AgentService_GetWorkloads_FullMethodName    = "/microseg.AgentService/GetWorkloads"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentServiceClient interface {
	// 配置策略
	ConfigPolicy(ctx context.Context, in *PolicyConfig, opts ...grpc.CallOption) (*ConfigResponse, error)
	// 配置组策略模式
	ConfigGroupMode(ctx context.Context, in *GroupModeConfig, opts ...grpc.CallOption) (*ConfigResponse, error)
	// 配置内部子网
	ConfigSubnets(ctx context.Context, in *SubnetConfig, opts ...grpc.CallOption) (*ConfigResponse, error)
	// 获取Agent状态
	GetStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AgentStatus, error)
	// 获取工作负载列表
	GetWorkloads(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*WorkloadList, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) ConfigPolicy(ctx context.Context, in *PolicyConfig, opts ...grpc.CallOption) (*ConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigResponse)
	err := c.cc.Invoke(ctx, AgentService_ConfigPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ConfigGroupMode(ctx context.Context, in *GroupModeConfig, opts ...grpc.CallOption) (*ConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigResponse)
	err := c.cc.Invoke(ctx, AgentService_ConfigGroupMode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ConfigSubnets(ctx context.Context, in *SubnetConfig, opts ...grpc.CallOption) (*ConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigResponse)
	err := c.cc.Invoke(ctx, AgentService_ConfigSubnets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AgentStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentStatus)
	err := c.cc.Invoke(ctx, AgentService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetWorkloads(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*WorkloadList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkloadList)
	err := c.cc.Invoke(ctx, AgentService_GetWorkloads_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
type AgentServiceServer interface {
	// 配置策略
	ConfigPolicy(context.Context, *PolicyConfig) (*ConfigResponse, error)
	// 配置组策略模式
	ConfigGroupMode(context.Context, *GroupModeConfig) (*ConfigResponse, error)
	// 配置内部子网
	ConfigSubnets(context.Context, *SubnetConfig) (*ConfigResponse, error)
	// 获取Agent状态
	GetStatus(context.Context, *Empty) (*AgentStatus, error)
	// 获取工作负载列表
	GetWorkloads(context.Context, *Empty) (*WorkloadList, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) ConfigPolicy(context.Context, *PolicyConfig) (*ConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigPolicy not implemented")
}
func (UnimplementedAgentServiceServer) ConfigGroupMode(context.Context, *GroupModeConfig) (*ConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigGroupMode not implemented")
}
func (UnimplementedAgentServiceServer) ConfigSubnets(context.Context, *SubnetConfig) (*ConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigSubnets not implemented")
}
func (UnimplementedAgentServiceServer) GetStatus(context.Context, *Empty) (*AgentStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedAgentServiceServer) GetWorkloads(context.Context, *Empty) (*WorkloadList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkloads not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_ConfigPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PolicyConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ConfigPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ConfigPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ConfigPolicy(ctx, req.(*PolicyConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ConfigGroupMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupModeConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ConfigGroupMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ConfigGroupMode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ConfigGroupMode(ctx, req.(*GroupModeConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ConfigSubnets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubnetConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ConfigSubnets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ConfigSubnets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ConfigSubnets(ctx, req.(*SubnetConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetWorkloads_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetWorkloads(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetWorkloads_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetWorkloads(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "microseg.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConfigPolicy",
			Handler:    _AgentService_ConfigPolicy_Handler,
		},
		{
			MethodName: "ConfigGroupMode",
			Handler:    _AgentService_ConfigGroupMode_Handler,
		},
		{
			MethodName: "ConfigSubnets",
			Handler:    _AgentService_ConfigSubnets_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _AgentService_GetStatus_Handler,
		},
		{
			MethodName: "GetWorkloads",
			Handler:    _AgentService_GetWorkloads_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "microseg.proto",
}

const (
	ControllerService_Register_FullMethodName          = "/microseg.ControllerService/Register"
	ControllerService_Heartbeat_FullMethodName         = "/microseg.ControllerService/Heartbeat"
	ControllerService_ReportConnections_FullMethodName = "/microseg.ControllerService/ReportConnections"
	ControllerService_ReportThreats_FullMethodName     = "/microseg.ControllerService/ReportThreats"
	ControllerService_ReportWorkload_FullMethodName    = "/microseg.ControllerService/ReportWorkload"
	ControllerService_GetPolicies_FullMethodName       = "/microseg.ControllerService/GetPolicies"
)

// ControllerServiceClient is the client API for ControllerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ControllerServiceClient interface {
	// Agent 注册
	Register(ctx context.Context, in *AgentInfo, opts ...grpc.CallOption) (*RegisterResponse, error)
	// Agent 心跳
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// 上报连接
	ReportConnections(ctx context.Context, in *ConnectionReport, opts ...grpc.CallOption) (*ReportResponse, error)
	// 上报威胁日志
	ReportThreats(ctx context.Context, in *ThreatReport, opts ...grpc.CallOption) (*ReportResponse, error)
	// 上报工作负载变更
	ReportWorkload(ctx context.Context, in *WorkloadEvent, opts ...grpc.CallOption) (*ReportResponse, error)
	// 获取策略
	GetPolicies(ctx context.Context, in *PolicyRequest, opts ...grpc.CallOption) (*PolicyList, error)
}

type controllerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewControllerServiceClient(cc grpc.ClientConnInterface) ControllerServiceClient {
	return &controllerServiceClient{cc}
}

func (c *controllerServiceClient) Register(ctx context.Context, in *AgentInfo, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, ControllerService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, ControllerService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) ReportConnections(ctx context.Context, in *ConnectionReport, opts ...grpc.CallOption) (*ReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportResponse)
	err := c.cc.Invoke(ctx, ControllerService_ReportConnections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) ReportThreats(ctx context.Context, in *ThreatReport, opts ...grpc.CallOption) (*ReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportResponse)
	err := c.cc.Invoke(ctx, ControllerService_ReportThreats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) ReportWorkload(ctx context.Context, in *WorkloadEvent, opts ...grpc.CallOption) (*ReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportResponse)
	err := c.cc.Invoke(ctx, ControllerService_ReportWorkload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) GetPolicies(ctx context.Context, in *PolicyRequest, opts ...grpc.CallOption) (*PolicyList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PolicyList)
	err := c.cc.Invoke(ctx, ControllerService_GetPolicies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControllerServiceServer is the server API for ControllerService service.
// All implementations must embed UnimplementedControllerServiceServer
// for forward compatibility.
type ControllerServiceServer interface {
	// Agent 注册
	Register(context.Context, *AgentInfo) (*RegisterResponse, error)
	// Agent 心跳
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// 上报连接
	ReportConnections(context.Context, *ConnectionReport) (*ReportResponse, error)
	// 上报威胁日志
	ReportThreats(context.Context, *ThreatReport) (*ReportResponse, error)
	// 上报工作负载变更
	ReportWorkload(context.Context, *WorkloadEvent) (*ReportResponse, error)
	// 获取策略
	GetPolicies(context.Context, *PolicyRequest) (*PolicyList, error)
	mustEmbedUnimplementedControllerServiceServer()
}

// UnimplementedControllerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControllerServiceServer struct{}

func (UnimplementedControllerServiceServer) Register(context.Context, *AgentInfo) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedControllerServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedControllerServiceServer) ReportConnections(context.Context, *ConnectionReport) (*ReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportConnections not implemented")
}
func (UnimplementedControllerServiceServer) ReportThreats(context.Context, *ThreatReport) (*ReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportThreats not implemented")
}
func (UnimplementedControllerServiceServer) ReportWorkload(context.Context, *WorkloadEvent) (*ReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportWorkload not implemented")
}
func (UnimplementedControllerServiceServer) GetPolicies(context.Context, *PolicyRequest) (*PolicyList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPolicies not implemented")
}
func (UnimplementedControllerServiceServer) mustEmbedUnimplementedControllerServiceServer() {}
func (UnimplementedControllerServiceServer) testEmbeddedByValue()                           {}

// UnsafeControllerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControllerServiceServer will
// result in compilation errors.
type UnsafeControllerServiceServer interface {
	mustEmbedUnimplementedControllerServiceServer()
}

func RegisterControllerServiceServer(s grpc.ServiceRegistrar, srv ControllerServiceServer) {
	// If the following call panics, it indicates UnimplementedControllerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControllerService_ServiceDesc, srv)
}

func _ControllerService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).Register(ctx, req.(*AgentInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_ReportConnections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectionReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).ReportConnections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerService_ReportConnections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).ReportConnections(ctx, req.(*ConnectionReport))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_ReportThreats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ThreatReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).ReportThreats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerService_ReportThreats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).ReportThreats(ctx, req.(*ThreatReport))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_ReportWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkloadEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).ReportWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerService_ReportWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).ReportWorkload(ctx, req.(*WorkloadEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_GetPolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).GetPolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerService_GetPolicies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).GetPolicies(ctx, req.(*PolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ControllerService_ServiceDesc is the grpc.ServiceDesc for ControllerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControllerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "microseg.ControllerService",
	HandlerType: (*ControllerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _ControllerService_Register_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _ControllerService_Heartbeat_Handler,
		},
		{
			MethodName: "ReportConnections",
			Handler:    _ControllerService_ReportConnections_Handler,
		},
		{
			MethodName: "ReportThreats",
			Handler:    _ControllerService_ReportThreats_Handler,
		},
		{
			MethodName: "ReportWorkload",
			Handler:    _ControllerService_ReportWorkload_Handler,
		},
		{
			MethodName: "GetPolicies",
			Handler:    _ControllerService_GetPolicies_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "microseg.proto",
}
